#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# Copyright (c) 2024-2025, Arm Limited.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# -----------------------------------------------------------------------------

"""
Utility to filter lcov/GCOV info files (as generated by generate_info_file.py)
so that unwanted source files/directories can be removed from the final report.
"""

import argparse
import fnmatch
import os
import re
from typing import Iterable, List, Optional


def _split_patterns(value: str) -> List[str]:
    if not value:
        return []
    return [p.strip() for p in value.split(",") if p.strip()]


def _candidate_paths(path: str, workspace: Optional[str]) -> List[str]:
    candidates = [path]
    if workspace:
        try:
            rel_path = os.path.relpath(path, workspace)
            if not rel_path.startswith(".."):
                candidates.append(rel_path)
        except ValueError:
            pass
    return candidates


def _strip_glob_tokens(pattern: str) -> str:
    return re.sub(r"[\*\?\[\]]", "", pattern)


def _matches(path: str, patterns: Iterable[str]) -> bool:
    for pattern in patterns:
        if fnmatch.fnmatch(path, pattern):
            return True

        cleaned = _strip_glob_tokens(pattern)
        if cleaned and cleaned in path:
            return True
    return False


def should_keep(path: str, includes: List[str], excludes: List[str], workspace: Optional[str]) -> bool:
    candidates = _candidate_paths(path, workspace)
    include_match = True if not includes else any(
        _matches(candidate, includes) for candidate in candidates
    )
    exclude_match = any(_matches(candidate, excludes)
                        for candidate in candidates) if excludes else False
    return include_match and not exclude_match


def filter_info_file(input_file: str, output_file: str, includes: List[str], excludes: List[str], workspace: Optional[str]):
    with open(input_file, "r", encoding="utf-8") as src, open(output_file, "w", encoding="utf-8") as dst:
        buffer: List[str] = []
        current_path: Optional[str] = None
        in_record = False

        for line in src:
            stripped = line.strip()

            if line.startswith("TN:") or line.startswith("SF:") or in_record:
                if not in_record:
                    buffer = []
                    current_path = None
                    in_record = True

                buffer.append(line)

                if line.startswith("SF:"):
                    current_path = line[len("SF:"):].strip()

                if stripped == "end_of_record":
                    if current_path is None:
                        raise RuntimeError(
                            "Malformed info file: record without SF line encountered")

                    if should_keep(current_path, includes, excludes, workspace):
                        dst.writelines(buffer)

                    buffer = []
                    current_path = None
                    in_record = False
                continue

            dst.write(line)


def main():
    parser = argparse.ArgumentParser(
        description="Filter unwanted sources from an lcov info file.")
    parser.add_argument("--input_file", required=True,
                        help="Path to the source info file.")
    parser.add_argument("--output_file", required=True,
                        help="Path for the filtered output info file.")
    parser.add_argument(
        "--include", help="Comma-separated glob patterns to keep (others dropped).", default="")
    parser.add_argument(
        "--exclude", help="Comma-separated glob patterns to drop.", default="")
    parser.add_argument(
        "--workspace", help="Workspace root; allows matching relative paths.", default=None)
    args = parser.parse_args()

    includes = _split_patterns(args.include)
    excludes = _split_patterns(args.exclude)

    if not includes and not excludes:
        raise SystemExit(
            "At least one include/exclude pattern must be provided for filtering.")

    filter_info_file(args.input_file, args.output_file,
                     includes, excludes, args.workspace)


if __name__ == "__main__":
    main()
